"""Edit table Position and User

Revision ID: 4757b98a26ed
Revises: ce0b32c70ec5
Create Date: 2022-02-19 19:47:31.379457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4757b98a26ed'
down_revision = 'ce0b32c70ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=200), nullable=True),
    sa.Column('birth_place', sa.String(length=200), nullable=True),
    sa.Column('birthday', sa.Integer(), nullable=True),
    sa.Column('staff_identity', sa.String(length=50), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff')
    # ### end Alembic commands ###
